Nazar yavor26/service provider statuses #955 and #969
ita-social-projects/OoS-Backend pull request #1000
Opened 2023-02-08 18:01 UTC by NazarYavor26

2023-02-09 18:28 UTC, DmyMi requested changes

2023-02-09 18:28 UTC, DmyMi commented on OutOfSchool/OutOfSchool.ElasticsearchData/OutOfSchool.ElasticsearchData.csproj
> +    <ProjectReference Include="..\OutOfSchool.DataAccess\OutOfSchool.DataAccess.csproj" />
Please move `ProviderStatus` enum to Common project.

And remove this dependency on DataAccess project.

2023-02-09 18:28 UTC, DmyMi commented on OutOfSchool/OutOfSchool.ElasticsearchData/Models/WorkshopES.cs
> +    public ProviderStatus ProviderStatus { get; set; }
i don't see any logic the allows you to update this field when the provider status changes for provider in database.

Unless you make a force update to the workshop in any way in database using workshop combiner methods, any updates to provider will not be synchronised to Elastic and this field will not hold up to date information.

2023-02-20 15:53 UTC, DmyMi approved these changes

2023-02-20 21:54 UTC, alrom approved these changes

2023-02-21 12:27 UTC, merged