Added security HTTP headers.
ita-social-projects/OoS-Backend pull request #1025
Opened 2023-03-16 11:19 UTC by andriitsylia

2023-03-16 13:53 UTC, alrom approved these changes

2023-03-20 06:57 UTC, DmyMi requested changes

2023-03-20 06:57 UTC, DmyMi commented on OutOfSchool/OutOfSchool.Common/Extensions/Startup/SecurityHttpHeadersExtensions.cs
> +                    builder.AddCustomDirective("script-src-elem", "self");
this is the config for angular :) need to see what needs to be added for WebMVC/Razor pages on identity and should it be present in web api or not

2023-03-20 06:57 UTC, DmyMi commented on OutOfSchool/OutOfSchool.IdentityServer/OutOfSchool.IdentityServer.csproj
> +    <PackageReference Include="NetEscapades.AspNetCore.SecurityHeaders" Version="0.18.0" />
if we import it to common, we automatically have it in every project that depends on common. No need to have it here

2023-03-20 06:58 UTC, DmyMi requested changes

2023-03-20 06:58 UTC, DmyMi commented on OutOfSchool/OutOfSchool.WebApi/OutOfSchool.WebApi.csproj
> +	  <PackageReference Include="NetEscapades.AspNetCore.SecurityHeaders" Version="0.18.0" />
same, do not need to import here

2023-03-22 13:47 UTC, merged