Fix total amount providers
ita-social-projects/OoS-Backend pull request #1326
Opened 2023-12-11 15:29 UTC by VitaliyYuras

2023-12-11 15:36 UTC, DmyMi requested changes

2023-12-11 15:36 UTC, DmyMi commented on OutOfSchool/OutOfSchool.WebApi/Services/ExternalExportProviderService.cs
> +            int count = providerRepository.CountWithDeleted();
This is only the first part :) total amount should reflect the provided filter. Which means you need to also use the `updatedAfter` if it is present for count.

If we provide this value, we need to know only the total amount of providers that were changed or who's workshops have been changed after the given date (like you use it in `GetAllUpdatedProviders`).

2023-12-11 16:06 UTC, VadymLevkovskyi approved these changes

2023-12-12 12:11 UTC, DmyMi approved these changes

2023-12-12 12:12 UTC, merged