[Provider] Upload the list of employees
ita-social-projects/OoS-Backend pull request #1621
Opened 2024-12-25 19:09 UTC by HlibBondarev

1) Added UploadEmployeeDto class for uploading new employees.
2) Changed IProviderService interface - added method signature: Task UploadEmployeesForProvider(Guid id, UploadEmployeeDto[] data);
3) Changed ProviderService class:
- injected repositories for Individual, Official and Position to the service;
- added async method: Task UploadEmployeesForProvider(Guid id, UploadEmployeeDto[] data).
4) Changed ProviderServiceV2 class: injected repositories for Individual, Official and Position to the service.
5) Changed MappingProfile class: added mapping UploadEmployeeDto => Individual and Individual => UploadEmployeeDto.
6) Changed Constants class: added constants - MaxIndividualNameLength, MinIndividualNameLength and MaxNumberOfEmployeesToUpload.
7) Changed Position class: added default value (string.Empty) for properties - GenitiveName and ClassifierType. 
8) Changed User class: reodered properties and added comment - TODO. 
9) Added ProviderController class: added action - async Task<IActionResult> Upload(Guid id, [FromBody] UploadEmployeeDto[] uploadEployees). 
10) Changed tests in classes ProviderServiceTests, ProviderServiceV2, ProviderServiceTests and  ProviderServiceUpdate - added mocks of repositories for Individual, Official and Position.

2025-01-02 16:38 UTC, h4wk13 requested changes
As for me - it is not clear what is going on in many places in `ProviderService`.
I would ask for refactoring of it.

2025-01-02 16:38 UTC, h4wk13 commented on OutOfSchool/OutOfSchool.BusinessLogic/Services/ProviderServices/ProviderService.cs
> +        logger.LogInformation("Upload employees for provider was started.");
It does not look like info, it looks like `Debug`

2025-01-02 16:38 UTC, h4wk13 commented on OutOfSchool/OutOfSchool.BusinessLogic/Services/ProviderServices/ProviderService.cs
> +            throw new InvalidOperationException(errorMessage);
`ArgumentOutOfRangeException` ?

2025-01-02 16:38 UTC, h4wk13 commented on OutOfSchool/OutOfSchool.BusinessLogic/Services/ProviderServices/ProviderService.cs
> +            throw new InvalidOperationException(errorMessage);
`ArgumentOutOfRangeException` ?

2025-01-02 16:38 UTC, h4wk13 commented on OutOfSchool/OutOfSchool.BusinessLogic/Services/ProviderServices/ProviderService.cs
> +        var existingIndividuals = (await individualRepository.GetByFilter(i => data.Select(e => e.Rnokpp).Contains(i.Rnokpp))
please move `data.Select(e => e.Rnokpp)` into a local variable 
And how long that list might be ?

2025-01-02 16:38 UTC, h4wk13 commented on OutOfSchool/OutOfSchool.BusinessLogic/Services/ProviderServices/ProviderService.cs
> +        // Circle to add individuals to DB and populate the Dictionary for uploading employees
`Circle` -> `loop` ?

2025-01-03 09:49 UTC, HlibBondarev commented on OutOfSchool/OutOfSchool.BusinessLogic/Services/ProviderServices/ProviderService.cs
> +        logger.LogInformation("Upload employees for provider was started.");
Ok, replaced logger.LogInformation() with logger.LogDebug()

2025-01-03 09:50 UTC, HlibBondarev commented on OutOfSchool/OutOfSchool.BusinessLogic/Services/ProviderServices/ProviderService.cs
> +            throw new InvalidOperationException(errorMessage);
Ok, replaced InvalidOperationException with ArgumentOutOfRangeException

2025-01-03 09:50 UTC, HlibBondarev commented on OutOfSchool/OutOfSchool.BusinessLogic/Services/ProviderServices/ProviderService.cs
> +            throw new InvalidOperationException(errorMessage);
Ok, replaced InvalidOperationException with ArgumentOutOfRangeException

2025-01-03 09:53 UTC, HlibBondarev commented on OutOfSchool/OutOfSchool.BusinessLogic/Services/ProviderServices/ProviderService.cs
> +        var existingIndividuals = (await individualRepository.GetByFilter(i => data.Select(e => e.Rnokpp).Contains(i.Rnokpp))
Ok, moved data.Select(e => e.Rnokpp) into a local variable.
The number of members in this list is limited by a constant - MaxNumberOfEmployeesToUpload.
According to requirments MaxNumberOfEmployeesToUpload = 100

2025-01-03 09:53 UTC, HlibBondarev commented on OutOfSchool/OutOfSchool.BusinessLogic/Services/ProviderServices/ProviderService.cs
> +        // Circle to add individuals to DB and populate the Dictionary for uploading employees
Ok, Changed Circle -> loop

2025-01-07 11:11 UTC, DmyMi approved these changes

2025-01-07 11:51 UTC, DmyMi approved these changes

2025-01-07 11:52 UTC, merged