Refactoring/update identifier data type for selected entities
ita-social-projects/OoS-Backend pull request #412
Opened 2021-10-16 16:25 UTC by h4wk13

2021-10-19 18:26 UTC, OlhaHoliak commented on OutOfSchool/OutOfSchool.DataAccess/Models/Teacher.cs
>          public long WorkshopId { get; set; }
Guid?

2021-10-19 18:39 UTC, OlhaHoliak commented on OutOfSchool/OutOfSchool.WebApi/Services/ChatMessageService.cs
> +                    return;
should not we log that chat message was null?

2021-10-20 09:00 UTC, VadymLevkovskyi requested changes

2021-10-21 19:00 UTC, h4wk13 commented on OutOfSchool/OutOfSchool.ElasticsearchData/Models/WorkshopES.cs
> +        public Guid Id { get; set; }
Haven't seen such attributes in other ES models.
Should it be separate task ?

2021-11-01 17:57 UTC, h4wk13 commented on OutOfSchool/Tests/OutOfSchool.Tests.Common/TestDataGenerators/ApplicationDTOsGenerator.cs
> +        private static readonly Faker<ApplicationDto> faker = new Faker<ApplicationDto>()
Do we really need comments on private fields ?

2021-11-03 12:36 UTC, VadymLevkovskyi approved these changes

2021-11-03 12:56 UTC, merged