Necheporenko/Added a rejection message
ita-social-projects/OoS-Backend pull request #445
Opened 2021-11-26 13:31 UTC by BHy4uk

Added a rejection message after application status is changed to rejected

2021-12-06 11:29 UTC, DmyMi requested changes

2021-12-06 11:29 UTC, DmyMi commented on OutOfSchool/OutOfSchool.DataAccess/Repository/ApplicationRepository.cs
> +            if (application.Status != ApplicationStatus.Rejected)
repository shouldn't contain logic. Need to check the status in controller or service

2021-12-08 14:39 UTC, DmyMi approved these changes

2021-12-22 10:16 UTC, toherberg approved these changes

2021-12-24 13:14 UTC, SergeyNovitsky approved these changes

2021-12-29 12:09 UTC, yfedo approved these changes

2021-12-29 17:18 UTC, merged